compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.8.0.cjs

supportedArchitectures:
  os: ["linux", "current"]
  cpu: ["current", "arm64"]
  libc: ["current", "glibc", "musl"]
