compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - linux
    - current

yarnPath: .yarn/releases/yarn-4.8.1.cjs
