sonar.projectKey=potibm_kasseapparat
sonar.organization=potibm

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=kasseapparat

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=backend,frontend
sonar.tests=backend,frontend

sonar.test.inclusions=**/*_test.go,**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx
sonar.exclusions=**/node_modules/**,frontend/playwright-report/**,frontend/dist/**

# Coverage Paths
sonar.go.coverage.reportPaths=backend/coverage.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info