version: "2"
run:
  concurrency: 4
linters:
  default: "fast"
  enable:
    - wsl_v5
  disable:
    - wsl
    - testpackage
    - funlen
    - cyclop
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/sirupsen/logrus"
              desc: not allowed
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples
    rules:
      - path: tests/e2e/init_test_sumup.go
        linters:
          - mnd
      - path: internal/app/utils/seed.go
        linters:
          - mnd
formatters:
  enable:
    - golines
  settings:
    golines:
      max-len: 120
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
