version: "2"
run:
  concurrency: 4
linters:
  default: "fast"
  enable:
    - wsl_v5
    - staticcheck
    - errcheck
    - depguard
    - govet
    - mnd
    - tagalign
  disable:
    - wsl
    - testpackage
    - funlen
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 4
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/sirupsen/logrus"
              desc: not allowed
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
    tagalign:
      order:
        - json
        - yaml
        - yml
        - toml
        - form
        - mapstructure
        - binding
        - validate
        - gorm
    cyclop:
      max-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - (^|/)examples(/|$)
      - (^|/)third_party(/|$)
      - (^|/)builtin(/|$)
    rules:
      - path: tests/e2e/init_test_sumup.go
        linters:
          - mnd
      - path: internal/app/utils/seed.go
        linters:
          - mnd
formatters:
  enable:
    - golines
  settings:
    golines:
      max-len: 120
      reformat-tags: false
  exclusions:
    generated: lax
    paths:
      - (^|/)examples(/|$)
      - (^|/)third_party(/|$)
      - (^|/)builtin(/|$)
