#!/usr/bin/env bash
#MISE description="Initial project setup"

# ensure .env files exist
cd backend && [ -f .env ] || cp .env.example .env
cd backend && [ -d data ] || mkdir data

# Dependencies
mise run deps:install

# Infra Check
docker info >/dev/null 2>&1 || (echo "❌ Docker is not running!" && exit 1)
mise run infra:up