#!/usr/bin/env bash
#MISE description="Lint backend code (pass --fix to auto-fix)"
#MISE dir="./backend"
#USAGE flag "--fix" help="Automatically fix linting issues"

set -e
FIX_MODE="${usage_fix:-false}"

echo "🚀 Backend (Auto-Fix: $FIX_MODE)"
mkdir -p cmd/assets
touch cmd/assets/index.html

if [ "$FIX_MODE" = "true" ]; then
    go fmt ./...
    golangci-lint run --fix
    dotenv-linter fix . --no-backup --ignore-checks QuoteCharacter,ValueWithoutQuotes
else
    golangci-lint run
    dotenv-linter check . --ignore-checks QuoteCharacter,ValueWithoutQuotes
fi