#!/usr/bin/env bash
#MISE description="Lint backend code (pass --fix to auto-fix)"
#MISE dir="{{cwd}}/backend"
#USAGE flag "--fix" help="Automatically fix linting issues"

set -e

echo "🚀 Backend (Auto-Fix: ${usage_fix:-false})"
mkdir -p cmd/assets
touch cmd/assets/index.html

if [ "$usage_fix" = "true" ]; then
    go fmt ./...
    golangci-lint run --fix
    dotenv-linter fix . --no-backup --ignore-checks QuoteCharacter,ValueWithoutQuotes
else
    golangci-lint run
    dotenv-linter check . --ignore-checks QuoteCharacter,ValueWithoutQuotes
fi