name: Docker Release Build

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract semver tags
        id: semver
        run: |
          RAW_TAG="${GITHUB_REF_NAME#v}"
          echo "version=$RAW_TAG" >> "$GITHUB_OUTPUT"
          echo "tag1=$RAW_TAG" >> "$GITHUB_OUTPUT"
          echo "tag2=$(echo $RAW_TAG | cut -d. -f1)" >> "$GITHUB_OUTPUT"
          echo "tag3=$(echo $RAW_TAG | cut -d. -f1-2)" >> "$GITHUB_OUTPUT"
          echo "tag4=latest" >> "$GITHUB_OUTPUT"

      - name: Generate build date
        id: meta
        run: echo "value=$(date --iso-8601=seconds)" >> "$GITHUB_OUTPUT"

      # Extract the version from the release output
      - name: Extract version (from semantic release)
        run: echo "${{ steps.semver.outputs.version }}" > VERSION

      - name: Build and push with Bake
        id: bake
        uses: docker/bake-action@v4
        with:
          push: true
          targets: kasseapparat
          set: |
            kasseapparat.tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.tag1 }}
            kasseapparat.tags+=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.tag3 }}
            kasseapparat.tags+=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.tag2 }}
            kasseapparat.tags+=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.tag4 }}
            kasseapparat.args.VERSION=${{ steps.semver.outputs.version }}
            kasseapparat.args.BUILD_DATE=${{ steps.meta.outputs.value }}
            kasseapparat.labels.org.opencontainers.image.version=${{ steps.semver.outputs.version }}
            kasseapparat.labels.org.opencontainers.image.created=${{ steps.meta.outputs.value }}
            kasseapparat.annotations=index,manifest:org.opencontainers.image.version=${{ steps.semver.outputs.version }}
            kasseapparat.annotations=index,manifest:org.opencontainers.image.created=${{ steps.meta.outputs.value }}

      - name: Sign image with Cosign
        run: |
          cosign sign --yes ${{ env.REGISTRY }}/${{ github.repository }}@${{ steps.bake.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: "1"
