name: Docker Image Publish DEV

on:
  workflow_dispatch:
  push:
    branches:
      - fix/container-bake

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Get timestamp
        id: meta
        run: echo "value=$(date --iso-8601=seconds)" >> "$GITHUB_OUTPUT"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push with Bake
        uses: docker/bake-action@v6
        with:
          push: true
          targets: kasseapparat
          set: |
            kasseapparat.tags=ghcr.io/${{ github.repository }}:${{ github.event.inputs.version }}
            kasseapparat.args.VERSION=${{ github.event.inputs.version }}
            kasseapparat.args.BUILD_DATE=${{ steps.meta.outputs.value }}
            kasseapparat.labels.org.opencontainers.image.version=${{ github.event.inputs.version }}
            kasseapparat.labels.org.opencontainers.image.created=${{ steps.meta.outputs.value }}
            kasseapparat.annotations=index,manifest:org.opencontainers.image.version=${{ github.event.inputs.version }}
            kasseapparat.annotations=index,manifest:org.opencontainers.image.created=${{ steps.meta.outputs.value }}
