name: Docker Dev Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image tag (e.g. 2.5.3-dev)'
        required: true

  push:
    branches:
      - fix/container-bake

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version to current date
        run: echo "$(date +%Y-%m-%d)" > VERSION

      - name: Setup QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate timestamp for BUILD_DATE
        id: meta
        run: echo "value=$(date --iso-8601=seconds)" >> "$GITHUB_OUTPUT"

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "value=${{ github.event.inputs.version }}" >> "$GITHUB_OUTPUT"
          else
            echo "value=dev-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi

      - name: Debug version and date
        run: |
          echo "Tag: ${{ steps.version.outputs.value }}"
          echo "Build date: ${{ steps.meta.outputs.value }}"

      - name: Build and push with Bake
        uses: docker/bake-action@v4
        with:
          push: true
          targets: kasseapparat
          set: |
            kasseapparat.tags=ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}
            kasseapparat.args.VERSION=${{ steps.version.outputs.value }}
            kasseapparat.args.BUILD_DATE=${{ steps.meta.outputs.value }}
            kasseapparat.labels.org.opencontainers.image.version=${{ steps.version.outputs.value }}
            kasseapparat.labels.org.opencontainers.image.created=${{ steps.meta.outputs.value }}
            kasseapparat.annotations=index,manifest:org.opencontainers.image.version=${{ steps.version.outputs.value }}
            kasseapparat.annotations=index,manifest:org.opencontainers.image.created=${{ steps.meta.outputs.value }}
