name: GHCR Cleanup

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch multi-platform package version SHAs
        id: multi-arch-digests
        run: |
          DIGESTS=$(docker manifest inspect ghcr.io/potibm/kasseapparat | jq -r '.manifests[].digest' | paste -s -d ' ' -)
          echo "multi-arch-digests=$DIGESTS" >> "$GITHUB_ENV"

      - name: Run container-retention-policy
        uses: snok/container-retention-policy@d3bdcf5ce9b05f685154e4a16c39233b245e3d53 # v3.1.0
        with:
          image-names: kasseapparat
          account: user
          cut-off: 60d
          keep-n-most-recent: 20
          token: ${{ secrets.GHCR_PAT }}
          skip-shas: ${{ env.multi-arch-digests }}
          dry-run: false
