name: GHCR Cleanup

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch multi-platform package version SHAs
        id: multi-arch-digests
        run: |
          DIGESTS=$(docker manifest inspect ghcr.io/potibm/kasseapparat | jq -r '.manifests[].digest' | paste -s -d ' ' -)
          echo "multi-arch-digests=$DIGESTS" >> $GITHUB_ENV

      - name: Run container-retention-policy
        uses: snok/container-retention-policy@v3.0.0
        with:
          image-names: kasseapparat
          account: user
          cut-off: 60d
          keep-n-most-recent: 20
          token: ${{ secrets.GHCR_PAT }}
          skip-shas: ${{ env.multi-arch-digests }}
          dry-run: false
